model:
  base_learning_rate: 4.5e-06
  target: taming.models.vqgan.VQModelRectCircularPad
  params:
    embed_dim: 3
    n_embed: 8192
    ddconfig:
      double_z: false
      z_channels: 256
      resolution:
      - 256
      - 512
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 100000
        disc_weight: 0.8
        codebook_weight: 1.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 5
    train:
      target: taming.data.Matterport3D.CustomTrain
      params:
        path: preprocess/Matterport.txt
    # validation:
    #   target: taming.data.Matterport3D.CustomTest
    #   params:
    #     path: 

lightning:
  trainer:
    precision: 16
    gpus: 0,1
